/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SAMRAHULRouteImport } from './routes/SAMRAHUL'
import { Route as SAMRAHULLoginRouteImport } from './routes/SAMRAHUL-login'
import { Route as CoachDashboardRouteImport } from './routes/coach-dashboard'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RegisterCoachRouteImport } from './routes/register-coach'
import { Route as RegisterStudentRouteImport } from './routes/register-student'
import { Route as StudentDashboardRouteImport } from './routes/student-dashboard'
import { Route as CoachSlugRouteImport } from './routes/coach.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SAMRAHULRoute = SAMRAHULRouteImport.update({
  id: '/SAMRAHUL',
  path: '/SAMRAHUL',
  getParentRoute: () => rootRouteImport,
} as any)
const SAMRAHULLoginRoute = SAMRAHULLoginRouteImport.update({
  id: '/SAMRAHUL-login',
  path: '/SAMRAHUL-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachDashboardRoute = CoachDashboardRouteImport.update({
  id: '/coach-dashboard',
  path: '/coach-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterCoachRoute = RegisterCoachRouteImport.update({
  id: '/register-coach',
  path: '/register-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterStudentRoute = RegisterStudentRouteImport.update({
  id: '/register-student',
  path: '/register-student',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student-dashboard',
  path: '/student-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachSlugRoute = CoachSlugRouteImport.update({
  id: '/coach/$slug',
  path: '/coach/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/SAMRAHUL': typeof SAMRAHULRoute
  '/SAMRAHUL-login': typeof SAMRAHULLoginRoute
  '/coach-dashboard': typeof CoachDashboardRoute
  '/coaches': typeof CoachesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-coach': typeof RegisterCoachRoute
  '/register-student': typeof RegisterStudentRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/coach/$slug': typeof CoachSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/SAMRAHUL': typeof SAMRAHULRoute
  '/SAMRAHUL-login': typeof SAMRAHULLoginRoute
  '/coach-dashboard': typeof CoachDashboardRoute
  '/coaches': typeof CoachesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-coach': typeof RegisterCoachRoute
  '/register-student': typeof RegisterStudentRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/coach/$slug': typeof CoachSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/SAMRAHUL': typeof SAMRAHULRoute
  '/SAMRAHUL-login': typeof SAMRAHULLoginRoute
  '/coach-dashboard': typeof CoachDashboardRoute
  '/coaches': typeof CoachesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-coach': typeof RegisterCoachRoute
  '/register-student': typeof RegisterStudentRoute
  '/student-dashboard': typeof StudentDashboardRoute
  '/coach/$slug': typeof CoachSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/SAMRAHUL'
    | '/SAMRAHUL-login'
    | '/coach-dashboard'
    | '/coaches'
    | '/login'
    | '/register'
    | '/register-coach'
    | '/register-student'
    | '/student-dashboard'
    | '/coach/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/SAMRAHUL'
    | '/SAMRAHUL-login'
    | '/coach-dashboard'
    | '/coaches'
    | '/login'
    | '/register'
    | '/register-coach'
    | '/register-student'
    | '/student-dashboard'
    | '/coach/$slug'
  id:
    | '__root__'
    | '/'
    | '/SAMRAHUL'
    | '/SAMRAHUL-login'
    | '/coach-dashboard'
    | '/coaches'
    | '/login'
    | '/register'
    | '/register-coach'
    | '/register-student'
    | '/student-dashboard'
    | '/coach/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SAMRAHULRoute: typeof SAMRAHULRoute
  SAMRAHULLoginRoute: typeof SAMRAHULLoginRoute
  CoachDashboardRoute: typeof CoachDashboardRoute
  CoachesRoute: typeof CoachesRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RegisterCoachRoute: typeof RegisterCoachRoute
  RegisterStudentRoute: typeof RegisterStudentRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  CoachSlugRoute: typeof CoachSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SAMRAHUL': {
      id: '/SAMRAHUL'
      path: '/SAMRAHUL'
      fullPath: '/SAMRAHUL'
      preLoaderRoute: typeof SAMRAHULRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SAMRAHUL-login': {
      id: '/SAMRAHUL-login'
      path: '/SAMRAHUL-login'
      fullPath: '/SAMRAHUL-login'
      preLoaderRoute: typeof SAMRAHULLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach-dashboard': {
      id: '/coach-dashboard'
      path: '/coach-dashboard'
      fullPath: '/coach-dashboard'
      preLoaderRoute: typeof CoachDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-coach': {
      id: '/register-coach'
      path: '/register-coach'
      fullPath: '/register-coach'
      preLoaderRoute: typeof RegisterCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-student': {
      id: '/register-student'
      path: '/register-student'
      fullPath: '/register-student'
      preLoaderRoute: typeof RegisterStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-dashboard': {
      id: '/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/$slug': {
      id: '/coach/$slug'
      path: '/coach/$slug'
      fullPath: '/coach/$slug'
      preLoaderRoute: typeof CoachSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SAMRAHULRoute: SAMRAHULRoute,
  SAMRAHULLoginRoute: SAMRAHULLoginRoute,
  CoachDashboardRoute: CoachDashboardRoute,
  CoachesRoute: CoachesRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RegisterCoachRoute: RegisterCoachRoute,
  RegisterStudentRoute: RegisterStudentRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  CoachSlugRoute: CoachSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
